### ISSUE TITLE
Master Task List

### ISSUE THREAD

**Issue by cesar-osorio70** [cesar-osorio70/intro-to-github#5]
# Example of a task list.

- [ ] update index.d file
- [ ] update code on README.md
- [ ] update Main branch
